### ISSUE TITLE
DOC: update documentation style

### ISSUE THREAD

**Issue by matthew-powers-db** [mrpowers-io/quinn#263]
### Quinn version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://mrpowers.github.io/quinn/)

### Location of the documentation

all of them

### Documentation problem

syntax is off

### Suggested fix for documentation

```
- pymdownx.highlight:
  anchor_linenums: true
  line_spans: __span
  pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
```

This snippet should be added to quinn and (maybe) chispa. Otherwise syntax highlighting in docs is not working
